// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2mxby3FU7kTT4wwkqthr0YMjqlDAu48g',
    appId: '1:494022571579:web:c744d9d7b96f21be4b8e1e',
    messagingSenderId: '494022571579',
    projectId: 'pizza-app-v1',
    authDomain: 'pizza-app-v1.firebaseapp.com',
    storageBucket: 'pizza-app-v1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUQr81QTY9kPcHEgVwU0FUZO6Y8dshBKo',
    appId: '1:494022571579:android:ec33d57b94f26e3c4b8e1e',
    messagingSenderId: '494022571579',
    projectId: 'pizza-app-v1',
    storageBucket: 'pizza-app-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9nfBHGr5wBXN9p64kvr3MGQ6tQO38Ays',
    appId: '1:494022571579:ios:ca0de03d67766b474b8e1e',
    messagingSenderId: '494022571579',
    projectId: 'pizza-app-v1',
    storageBucket: 'pizza-app-v1.appspot.com',
    iosBundleId: 'com.example.updatePizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9nfBHGr5wBXN9p64kvr3MGQ6tQO38Ays',
    appId: '1:494022571579:ios:50a64554291d08164b8e1e',
    messagingSenderId: '494022571579',
    projectId: 'pizza-app-v1',
    storageBucket: 'pizza-app-v1.appspot.com',
    iosBundleId: 'com.example.updatePizzaApp.RunnerTests',
  );
}
